In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

#  Import and read the charity_data.csv.
import pandas as pd 
stroke_data_df = pd.read_csv("healthcare-dataset-stroke-data.csv")
stroke_data_df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Preprocessing**

In [3]:
# Drop the non-beneficial ID column.
stroke_df = stroke_data_df.drop(columns={'id'})

In [4]:
# Drop rows containing NaN
stroke_df = stroke_df.dropna()

In [5]:
# Convert categorical data to numeric with `pd.get_dummies`
encoded_stroke_data = pd.get_dummies(stroke_df)
encoded_stroke_data

age  hypertension  heart_disease  avg_glucose_level   bmi  stroke  \
0     67.0             0              1             228.69  36.6       1   
2     80.0             0              1             105.92  32.5       1   
3     49.0             0              0             171.23  34.4       1   
4     79.0             1              0             174.12  24.0       1   
5     81.0             0              0             186.21  29.0       1   
...    ...           ...            ...                ...   ...     ...   
5104  13.0             0              0             103.08  18.6       0   
5106  81.0             0              0             125.20  40.0       0   
5107  35.0             0              0              82.99  30.6       0   
5108  51.0             0              0             166.29  25.6       0   
5109  44.0             0              0              85.28  26.2       0   

      gender_Female  gender_Male  gender_Other  ever_married_No  ...  \
0                 0            1             0                0  ...   
2                 0            1             0                0  ...   
3                 1            0             0                0  ...   
4                 1            0             0                0  ...   
5                 0            1             0                0  ...   
...             ...          ...           ...              ...  ...   
5104              1            0             0                1  ...   
5106              1            0             0                0  ...   
5107              1            0             0                0  ...   
5108              0            1             0                0  ...   
5109              1            0             0                0  ...   

      work_type_Never_worked  work_type_Private  work_type_Self-employed  \
0                          0                  1                        0   
2                          0                  1                        0   
3                          0                  1                        0   
4                          0                  0                        1   
5                          0                  1                        0   
...                      ...                ...                      ...   
5104                       0                  0                        0   
5106                       0                  0                        1   
5107                       0                  0                        1   
5108                       0                  1                        0   
5109                       0                  0                        0   

      work_type_children  Residence_type_Rural  Residence_type_Urban  \
0                      0                     0                     1   
2                      0                     1                     0   
3                      0                     0                     1   
4                      0                     1                     0   
5                      0                     0                     1   
...                  ...                   ...                   ...   
5104                   1                     1                     0   
5106                   0                     0                     1   
5107                   0                     1                     0   
5108                   0                     1                     0   
5109                   0                     0                     1   

      smoking_status_Unknown  smoking_status_formerly smoked  \
0                          0                               1   
2                          0                               0   
3                          0                               0   
4                          0                               0   
5                          0                               1   
...                      ...                             ...   
510

In [6]:
# Split our preprocessed data into our features and target arrays
y = encoded_stroke_data["stroke"]
X = encoded_stroke_data.drop(["stroke"], axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [7]:
# Check the balance of our target values
y.value_counts()

0    4700
1     209
Name: stroke, dtype: int64

In [8]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# **Logistic Regression Model**
Attempt 1 using orignial data.

Something is clearly going wrong here, but I'm not sure what.

In [9]:
# Fit the model
# Instantiate the Logistic Regression model
logistic_regression_model = LogisticRegression(max_iter=200)

# Fit the model using training data
model = logistic_regression_model.fit(X_train_scaled, y_train)

In [10]:
# Make a prediction using the testing data
LR_pred = logistic_regression_model.predict(X_test_scaled)

In [11]:
# Print the balanced_accuracy score of the model
balanced_accuracy_score(y_test, LR_pred)

0.5

In [12]:
# Generate a confusion matrix for the model
matrix = confusion_matrix(y_test, LR_pred)
print(matrix)

[[1177    0]
 [  51    0]]


In [13]:
# Print the classification report for the model
report = classification_report(y_test, LR_pred)
print(report)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1177
           1       0.00      0.00      0.00        51

    accuracy                           0.96      1228
   macro avg       0.48      0.50      0.49      1228
weighted avg       0.92      0.96      0.94      1228



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Neural Network Model**
Attempt 1 using original data.

In [14]:
# Define the model
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 9
hidden_nodes_layer2 = 9
hidden_nodes_layer3 = 9

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 9)                 198       
                                                                 
 dense_1 (Dense)             (None, 9)                 90        
                                                                 
 dense_2 (Dense)             (None, 9)                 90        
                                                                 
 dense_3 (Dense)             (None, 1)                 10        
                                                                 
Total params: 388
Trainable params: 388
Non-trainable params: 0
_________________________________________________________________


In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
116/116 [==============================] - 4s 10ms/step - loss: 0.3433 - accuracy: 0.9571
Epoch 2/50
116/116 [==============================] - 1s 8ms/step - loss: 0.1859 - accuracy: 0.9571
Epoch 3/50
116/116 [==============================] - 1s 9ms/step - loss: 0.1661 - accuracy: 0.9571
Epoch 4/50
116/116 [==============================] - 1s 9ms/step - loss: 0.1582 - accuracy: 0.9571
Epoch 5/50
116/116 [==============================] - 1s 9ms/step - loss: 0.1521 - accuracy: 0.9571
Epoch 6/50
116/116 [==============================] - 1s 7ms/step - loss: 0.1489 - accuracy: 0.9571
Epoch 7/50
116/116 [==============================] - 1s 8ms/step - loss: 0.1464 - accuracy: 0.9571
Epoch 8/50
116/116 [==============================] - 1s 6ms/step - loss: 0.1440 - accuracy: 0.9571
Epoch 9/50
116/116 [==============================] - 1s 7ms/step - loss: 0.1422 - accuracy: 0.9571
Epoch 10/50
116/116 [==============================] - 1s 7ms/step - loss: 0.1406 - accuracy: 0.957

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

39/39 - 0s - loss: 0.1654 - accuracy: 0.9585 - 254ms/epoch - 7ms/step
Loss: 0.16544944047927856, Accuracy: 0.958469033241272


In [18]:
# Export our model to HDF5 file
# nn.save('Models/stroke_model_NN_1.h5')

# **K Nearest Neighbors**

In [19]:
# Instantiate the model with k = 3 neighbors
model = KNeighborsClassifier(n_neighbors=3)

In [20]:
# Train the model
model.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [21]:
# Create predictions
KN_pred = model.predict(X_test_scaled)

In [22]:
# Print confusion matrix
confusion_matrix(KN_pred,y_test)

array([[1168,   47],
       [   9,    4]])

In [23]:
# Print classification report
print(classification_report(KN_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.96      0.98      1215
           1       0.08      0.31      0.12        13

    accuracy                           0.95      1228
   macro avg       0.54      0.63      0.55      1228
weighted avg       0.98      0.95      0.97      1228



# **Random Forest**

It looks like this is having the same problem as the first Logistic Regression model, using the resampled data might help.

In [24]:
# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=500)

In [25]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [26]:
# Making predictions using the testing data
rf_pred = rf_model.predict(X_test_scaled)

In [27]:
# Print confusion matrix
confusion_matrix(rf_pred,y_test)

array([[1177,   51],
       [   0,    0]])

In [28]:
# Print classification report
print(classification_report(rf_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      1228
           1       0.00      0.00      0.00         0

    accuracy                           0.96      1228
   macro avg       0.50      0.48      0.49      1228
weighted avg       1.00      0.96      0.98      1228



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Resample Data with RandomOverSampler**

In [29]:
!pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [30]:

# Instantiate the random oversampler model
ros = RandomOverSampler()

# Fit the original training data to the random_oversampler model
X_R, y_R = ros.fit_resample(X_train, y_train)

In [31]:
# Count the distinct values of the resampled labels data
y_R.value_counts()

0    3523
1    3523
Name: stroke, dtype: int64

In [32]:
X_train_scaled_R = X_scaler.transform(X_R)

# **Neural Network Model 2**
Attempt 2 using RandomOverSampler

In [33]:
# Neural network model with RandomOverSampler
# Define the model
number_input_features = len(X_train_scaled_R[0])
hidden_nodes_layer1 = 9
hidden_nodes_layer2 = 9
hidden_nodes_layer3 = 9

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 9)                 198       
                                                                 
 dense_5 (Dense)             (None, 9)                 90        
                                                                 
 dense_6 (Dense)             (None, 9)                 90        
                                                                 
 dense_7 (Dense)             (None, 1)                 10        
                                                                 
Total params: 388
Trainable params: 388
Non-trainable params: 0
_________________________________________________________________


In [34]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [35]:
# Train the model
fit_model = nn.fit(X_train_scaled_R,y_R,epochs=50)

Epoch 1/50
221/221 [==============================] - 3s 4ms/step - loss: 0.5622 - accuracy: 0.7030
Epoch 2/50
221/221 [==============================] - 1s 5ms/step - loss: 0.4844 - accuracy: 0.7790
Epoch 3/50
221/221 [==============================] - 1s 5ms/step - loss: 0.4518 - accuracy: 0.8005
Epoch 4/50
221/221 [==============================] - 1s 6ms/step - loss: 0.4318 - accuracy: 0.8071
Epoch 5/50
221/221 [==============================] - 1s 6ms/step - loss: 0.4173 - accuracy: 0.8189
Epoch 6/50
221/221 [==============================] - 2s 8ms/step - loss: 0.4034 - accuracy: 0.8270
Epoch 7/50
221/221 [==============================] - 2s 9ms/step - loss: 0.3939 - accuracy: 0.8311
Epoch 8/50
221/221 [==============================] - 2s 10ms/step - loss: 0.3837 - accuracy: 0.8317
Epoch 9/50
221/221 [==============================] - 1s 6ms/step - loss: 0.3732 - accuracy: 0.8364
Epoch 10/50
221/221 [==============================] - 1s 5ms/step - loss: 0.3662 - accuracy: 0.834

In [36]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

39/39 - 0s - loss: 0.4671 - accuracy: 0.8143 - 338ms/epoch - 9ms/step
Loss: 0.4670688509941101, Accuracy: 0.8143322467803955


In [37]:
# Export our model to HDF5 file
# nn.save('Models/stroke_model_NN_2.h5')

# **Logistic Regression Model 2**
Attempt 2 using RandomOverSampler

In [38]:
# Logistic Regression model with RandomOverSampler
# Instantiate the Logistic Regression model
ros_logistic_regression_model = LogisticRegression(max_iter=200)

# Fit the model using the resampled training data
ros_model = logistic_regression_model.fit(X_train_scaled_R, y_R)

# Make a prediction using the testing data
ros_LR_pred = logistic_regression_model.predict(X_test_scaled)

In [39]:
# Print the balanced_accuracy score of the model 
balanced_accuracy_score(y_test, ros_LR_pred)

0.7595831875655954

In [40]:
# Generate a confusion matrix for the model
ros_matrix = confusion_matrix(y_test, ros_LR_pred)
print(ros_matrix)

[[888 289]
 [ 12  39]]


In [41]:
# Print the classification report for the model
ros_report = classification_report(y_test, ros_LR_pred)
print(ros_report)

              precision    recall  f1-score   support

           0       0.99      0.75      0.86      1177
           1       0.12      0.76      0.21        51

    accuracy                           0.75      1228
   macro avg       0.55      0.76      0.53      1228
weighted avg       0.95      0.75      0.83      1228



# **Neural Network Model 3**
Attempt 3 using Keras Tuner and RandomOverSampler

In [42]:
!pip install keras-tuner

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [59]:
import keras_tuner as kt

In [60]:
# Set value for input_dim
number_input_features = len(X_train_scaled_R[0])

# Create method for new Sequential model with hyperparameter option
def create_model (hp):
  nn_model = tf.keras.models.Sequential()

  # Activation function options
  activation = hp.Choice('activation', ['relu', 'tanh', 'sigmoid'])

  # Number of neurons in first layer
  nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units', min_value=1, max_value=10, step=2),
                                     activation=activation, input_dim=number_input_features))
  
  # Number of hidden layers and neurons per layer
  for i in range(hp.Int('num_layers', 1, 3)):
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i), min_value=1, max_value=10, step=2), activation=activation))

  nn_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

  # Compile the model
  nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

  return nn_model


In [61]:
# Create tuner with keras_tuner
tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

In [62]:
# Run tuner search for best hyperparameters
tuner.search(X_train_scaled_R,y_R,epochs=20,validation_data=(X_test_scaled,y_test))

In [47]:
# Find most accurate model
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'relu',
 'first_units': 1,
 'num_layers': 5,
 'units_0': 9,
 'units_1': 1,
 'units_2': 1,
 'units_3': 13,
 'units_4': 5,
 'units_5': 17,
 'tuner/epochs': 3,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 2,
 'tuner/round': 0}

In [48]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

39/39 - 0s - loss: 0.6922 - accuracy: 0.9585 - 327ms/epoch - 8ms/step
Loss: 0.6921735405921936, Accuracy: 0.958469033241272


# **K Nearest Neighbors 2**
Attempt 2 using RandomOverSampler

In [49]:
# Instantiate the model with k = 3 neighbors
model = KNeighborsClassifier(n_neighbors=3)

In [50]:
# Train the model
model.fit(X_train_scaled_R, y_R)

KNeighborsClassifier(n_neighbors=3)

In [51]:
# Create predictions
ros_KN_pred = model.predict(X_test_scaled)

In [52]:
# Print confusion matrix
confusion_matrix(ros_KN_pred,y_test)

array([[1097,   45],
       [  80,    6]])

In [53]:
# Print classification report
print(classification_report(ros_KN_pred,y_test))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95      1142
           1       0.12      0.07      0.09        86

    accuracy                           0.90      1228
   macro avg       0.52      0.52      0.52      1228
weighted avg       0.87      0.90      0.89      1228



# **Random Forest**
Attempt 2 using RandomOverSampler

In [54]:
# Create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=500)

In [55]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled_R, y_R)

In [56]:
# Making predictions using the testing data
ros_rf_pred = rf_model.predict(X_test_scaled)

In [57]:
# Print confusion matrix
confusion_matrix(ros_rf_pred,y_test)

array([[1166,   49],
       [  11,    2]])

In [58]:
# Print classification report
print(classification_report(ros_rf_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.96      0.97      1215
           1       0.04      0.15      0.06        13

    accuracy                           0.95      1228
   macro avg       0.51      0.56      0.52      1228
weighted avg       0.98      0.95      0.97      1228

